# Generated by Django 4.2.1 on 2023-07-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchActivities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=100),
        ),
    ]
