# Generated by Django 4.2.1 on 2023-07-05 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('churchActivities', '0003_remove_activity_time_activity_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
