# Generated by Django 4.2.1 on 2023-07-10 17:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchActivities', '0004_announcement_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
