# Generated by Django 4.2.1 on 2023-07-31 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('churchActivities', '0005_alter_member_managers_alter_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Regular Member', 'Regular Member'), ('Visitor', 'Visitor')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
