# Generated by Django 4.2.1 on 2023-08-27 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('churchActivities', '0007_titheoffering'),
    ]

    operations = [
        migrations.AddField(
            model_name='titheoffering',
            name='quarter',
            field=models.CharField(choices=[('First QUARTER', 'First QUARTER'), ('Second QUARTER', 'Second QUARTER'), ('Third QUARTER', 'Third QUARTER'), ('Forth QUARTER', 'Forth QUARTER')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
