# Generated by Django 4.2.1 on 2023-08-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchActivities', '0008_titheoffering_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titheoffering',
            name='quarter',
            field=models.CharField(choices=[('First QUARTER', 'First QUARTER'), ('Second QUARTER', 'Second QUARTER'), ('Third QUARTER', 'Third QUARTER'), ('Forth QUARTER', 'Forth QUARTER')], max_length=60),
        ),
    ]
