# Generated by Django 4.2.1 on 2023-09-04 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchActivities', '0009_alter_titheoffering_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hod',
        ),
        migrations.AlterField(
            model_name='titheoffering',
            name='quarter',
            field=models.CharField(choices=[('First Quarter', 'First Quarter'), ('Second Quarter', 'Second Quarter'), ('Third Quarter', 'Third Quarter'), ('Forth Quarter', 'Forth Quarter')], max_length=60),
        ),
        migrations.CreateModel(
            name='DepartmentHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='churchActivities.department')),
                ('hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
