# Generated by Django 4.2.1 on 2023-09-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchActivities', '0011_rename_departement_departmenthod_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthod',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='churchActivities.department', unique=True),
        ),
    ]
