# Generated by Django 4.2.1 on 2023-09-07 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchActivities', '0012_alter_departmenthod_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('Tithe', 'Tithe'), ('Offerings', 'Offerings'), ('Umusaruro', 'Umusaruro'), ('Inyubako', 'Inyubako'), ('Iteraniro Rikuru', 'Iteraniro Rikuru'), ('Donation', 'Donation')], max_length=100)),
                ('amount_given', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchActivities.department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
