# Generated by Django 4.2.1 on 2023-09-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchActivities', '0013_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_given',
            field=models.FloatField(),
        ),
    ]
